### ISSUE TITLE
Impressum erstellen

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/codeformuenster.github.io#39]
Aussage von Fiona im OKFN-Slack: das von codefor.de nehmen.
https://github.com/okfde/codefor.de/blob/gh-pages/impressum/index.html

Wir wollen ja rechtlich auch auf der sicheren Seite sein..

**Comment by tomsrocket** [comment]
Habe einen Pullrequest gestellt, der die o.g. Impressumsseite zu unserer Homepage im Footer hinzufügt.
