### ISSUE TITLE
NaN für Processbar bei Projekten ohne Issues

### ISSUE THREAD

**Issue by stawi** [codeformuenster/codeformuenster.github.io#50]
# NaN Processbar bei Projekten ohne Issues

**Browser:** Chrome version 64.0.3282.186 
**OS:** Windows 10 64 Bit

Projekte auf der Website, welche noch keine Issues hatten, bekommen eine Processbar mit NaN.
Außerdem wird statt "Noch keine Issues" oder "0/0 Issues" nur "Issues" angezeigt.

Ein weiterer Verbesserungsvorschlag wäre, einen Link direkt zu den Issues zu geben - zumindest bei den Projekten, bei denen noch offene Issues bestehen. 

![image](https://user-images.githubusercontent.com/3306851/36634970-7409ec6c-19ad-11e8-8251-d8e9303621ba.png)

**Comment by silberzwiebel** [comment]
Danke für das Feedback und entschuldige die späte Antwort! Vermutlich bekommen wir Deine Anregungen schneller umgesetzt, wenn Du sie selber in die Hand nimmst ;).
Komm doch einfach mal zu unseren Treffen vorbei! :)
