### ISSUE TITLE
Link zur Uni ist falsch

### ISSUE THREAD

**Issue by hajothelen** [codeformuenster/codeformuenster.github.io#51]
https://github.com/codeformuenster/codeformuenster.github.io/blob/a4d5e8860144c66ea347d0379ad27080ff4eab67/index.html#L124

Statt `href="http://ifgi.uni-muester.de"` muss es natürlich `href="http://ifgi.uni-muenster.de"` heißen

**Comment by silberzwiebel** [comment]
Danke für den Hinweis! Wärst Du so nett einen Pull Request zu erstellen, dann müssen wir nur noch einen Klick machen? 🦄
