### ISSUE TITLE
Blog Eintrag schreiben zum Münsterhack

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/codeformuenster.github.io#59]

**Comment by tomsrocket** [comment]
Wir könnten etwas zum Münsterhack schreiben, und auf unser Archiv-Repository verlinken.

**Comment by silberzwiebel** [comment]
Vielleicht schaffen wir es ja dieses Jahr? Noch nah genug dran ...

**Comment by quassy** [comment]
Oder dieses Jahr? :)
