### ISSUE TITLE
Docker image borken?

### ISSUE THREAD

**Issue by ScholliYT** [codeformuenster/codeformuenster.github.io#63]
Hi,
wollte mal wieder etwas weiter entwicklen. Bekomme allderings diese schöne Fehlermeldung beim lokalen Hosten der website. Hat jemand eine Idee, was da falsch läuft?

![screenshot_242](https://user-images.githubusercontent.com/12571895/52600964-a5341180-2e5d-11e9-9079-59d591ef0c62.png)
![screenshot_243](https://user-images.githubusercontent.com/12571895/52600963-a5341180-2e5d-11e9-8bf4-0090c7326e24.png)

Habe das ganze jetzt nochmal auf einer frischen VM getestet. Selber Fehler :(

**Comment by thunfischtoast** [comment]
Moin,

versuch mal den docker-Befehl mit ```sudo``` vorn weg zu starten. Falls das nichts hilft: Guck mal, ob bei ```echo $PWD``` dein aktueller Pfad rauskommt. Wenn nicht könntest du das $PWD mal durch den absoluten Pfad zum Repo auf deiner Maschine ersetzen.

Docker läuft nicht immer sauber in VMs, insbesondere wenn das Host-System Windows ist. In welcher VM führst du das aus? Und was ist dein Host-System?

**Comment by ScholliYT** [comment]
Habe mir eine ubuntu 18.04.1 LTS auf Windows 10 mit Hyper-V gemacht.

**Comment by ScholliYT** [comment]
Bekomme leider den gleichen Fehler mit:
`sudo docker run -it --rm -v /home/tom/Dokumente/GitRepos/codeformuenster.github.io:/usr/src/app -p "4000:4000" starefossen/github-pages
`

**Comment by ubergesundheit** [comment]
Versuch mal die ne neue Version des images zu ziehen (docker pull)

Der Pfad muss im image existieren, auf deinem lokalen host bringt dir die nix (zweiter screenshot)

**Comment by ScholliYT** [comment]
ich kann leider auch nicht so genau sagen, warum der Fehler jetzt weg ist, aber erstmal läufts wieder. Habe das Repo nochmal neu geklont. Dann gings plötzlich o_O 
Eigentlich müsste der Fehler auf einer neuen VM wo das repo auch neu geladen wurde auch weg sein.

**Comment by ScholliYT** [comment]
Hat wohl was damit zu tun, dass ich einen virtualenv ordner im Stammverzeichnis des Projekts hatte.
