### ISSUE TITLE
Meetup Termin wird nicht mehr auf der Homepage angezeigt

### ISSUE THREAD

**Issue by tomsrocket** [codeformuenster/codeformuenster.github.io#72]
Wir machen da im code einen apicall, der scheint nicht mehr zu gehen: 
https://api.meetup.com/2/events?callback=?&sign=true&status=upcoming&group_urlname=OK-Lab-Munster&format=json&key=48406a31956272b2f12c3965547d

**Comment by silberzwiebel** [comment]
Die scheinen da irgendwie was an der Authentifizeirung geändert zu haben. Statt API-key geht jetzt nur noch OAuth2. Sieht m.E. ziemlich nervig aus. Dabei ist die Info doch eh öffentlich...
Wir sollten aber ohnehin einfach in den Text schreiben, dass wir uns jede Woche treffen, oder?

Ansonsten wäre das ja vielleicht ja eine Gelegenheit, zu einem anderem Veranstaltungstool zu wechseln? Habe @ThorbenJensen auf https://gettogether.community/data-munching/ gefunden...

**Comment by ubergesundheit** [comment]
+1 für anderes Veranstaltungstool

**Comment by tomsrocket** [comment]
Fixed thanks to @quassy
