### ISSUE TITLE
Netlify für branch previews aktivieren

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/codeformuenster.github.io#79]

**Comment by ubergesundheit** [comment]
Deploy previews sind aktiviert.

**Comment by quassy** [comment]
Klingt cool! Unter welcher URL find ich dann z.B. den Branch `verkehrsunfaelle-blogpost`?

**Comment by ubergesundheit** [comment]
Jeder commit in einem pull request sollte das ab jetzt eigentlich triggern. Vorher sollten wir noch #85 machen
