### ISSUE TITLE
Fathom tracking für deploy previews deaktivieren

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/codeformuenster.github.io#85]
Seit 9c834cef481bc3707e5a9f1684a963b045f2da71 werden Besucher mit unserer Fathom Instanz gezählt. 

Dies sollte nur über codeformuenster.org passieren, für keine anderen Instanzen.

**Comment by quassy** [comment]
#86 works for me und beantwortet auch gleich die Frage, [wo die Previews auftauchen](https://deploy-preview-86--codeformuensterorg.netlify.com/) :wink:

**Comment by ubergesundheit** [comment]
Danke!
