### ISSUE TITLE
Wir in der Presse

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/codeformuenster.github.io#91]
Könnten wir mal sammeln und verlinken auf unserer Seite

Liste WIP!
| Wann | Wer | Thema | Link |
| --- | --- | --- | --- |
| 2014-02-19 | Westfälische Nachrichten | Ankündigung Open Data Day 2014 | https://www.wn.de/Muenster/2014/02/1454239-Daten-nutzbar-machen-Open-Data-Day-in-Muenster |
| 2014-02-23 | Westfälische Nachrichten | Open Data Day 2014 | https://www.wn.de/Muenster/2014/02/1459271-Opendataday-im-Medienhaus-Aschendorff-Der-schnelle-Weg-zum-naechsten-Glascontainer |
| 2015-02-13 | Westfälische Nachrichten | Ankündigung Open Data Day 2015 | https://www.wn.de/Muenster/2015/02/1882869-Aktivisten-Treffen-am-21.-Februar-Offene-Daten-als-digitale-Werkzeuge |
| 2015-02-22 | Westfälische Nachrichten | Bericht Open Data Day 2015 | https://www.wn.de/Muenster/2015/02/1895977-Mehr-offene-Daten-gefordert-Open-Data-Day-Rat-beschaeftigt-sich-demnaechst-mit-dem-Thema |
| 2019-10-23 | Westfälische Nachrichten | Unfalldaten Karte | https://www.wn.de/Muenster/Stadtteile/Hiltrup/4007359-Interaktive-Unfallkarte-zeigt-Gefahrenpunkte-in-Hiltrup-Hier-kracht-es-am-Haeufigsten |
| 2017-03-06 | Westfälische Nachrichten | Bericht Open Data Day 2017 | https://www.wn.de/Muenster/Muenster/2017/03/2729570-Amtliche-Daten-im-Netz-Digitale-Buergerbeteiligung |
| 2020-03-09 | Westfälische Nachrichten | Bericht Open Data Day 2020 | https://www.wn.de/Muenster/4166309-Open-Data-Day-in-der-Stadtbuecherei-Leicht-den-Ueberblick-gewinnen |

**Comment by thunfischtoast** [comment]
|Wann|Wer|Thema|Link|
|---------|-------|-----------|-------|
|2018-03-02|Kommune21|Open Data Day 2018|https://www.kommune21.de/meldung_28415_Tag+der+offenen+Daten.html
|2019-08-07|ADFC|Open Data Workshop/Verkehrsunfalldaten|https://www.adfc-nrw.de/kreisverbaende/kv-muenster/ortsgruppen/ortsgruppe-kopiervorlage/adfc-ortsgruppe-name/aktuelles/article/terminankuendigung-open-data-workshop-fuer-vereine.html|

**Comment by silberzwiebel** [comment]
Wann | Wer | Thema | Link
--- | --- | --- | ---
2020-03-28 | Klima-Initiative Münster | Klimawatch (nur zwei Sätze) | https://www.stadt-muenster.de/fileadmin//user_upload/stadt-muenster/67_klima/pdf/MS-Klimainfo_2020-03.pdf

**Comment by ubergesundheit** [comment]
Geschlossen wegen #95
